Add timer event.
mishaglik/Elpidifor-s-legacy pull request #40
Opened 2022-11-30 07:50 UTC by XDLoLiK

2022-11-30 07:53 UTC, mishaglik requested changes
Time is not specified.

2022-11-30 07:53 UTC, mishaglik commented on tools.hpp
> +        uint64_t time;
What is time?

2022-11-30 07:56 UTC, mishaglik commented on tools.hpp
> +        uint64_t time;
Ok

2022-11-30 07:57 UTC, mishaglik approved these changes
LGTM

2022-11-30 07:57 UTC, mishaglik commented
Thank for contributing in our repository.

2022-11-30 07:57 UTC, merged

2022-12-05 08:10 UTC, Lord-KA commented
Maybe [squash](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together) commits next time?